# Generated by Django 3.0 on 2019-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191208_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
