# Generated by Django 3.0 on 2019-12-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='compliant_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ComplaintState'),
        ),
    ]
