# Generated by Django 3.0 on 2019-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191211_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='responsible_response_date',
            new_name='tlp_response_date',
        ),
        migrations.AddField(
            model_name='complaint',
            name='tr_response_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
