# Generated by Django 3.0 on 2019-12-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191211_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='compliant_state',
            new_name='complaint_state',
        ),
    ]
